### ISSUE TITLE
chore: Develop 브런치 Vercel 에 Storybook 연결 작업

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#102]
## 📌 작업 내용

- Vercel 에 프로젝트 develop 브런치 연결 
- develop 브런치 연결 시 stroybook이 실행되도록 연결
- Vercel 띄워지는 국가 한국 or Asia 쪽으로 지정 필요(해당 작업을 안 하면 로딩 속도가 오래 걸립니다.)

## ✅ To-Do

- [ ] Vercel에 FE 리포지토리 연결
- [ ] develop 브런치 연동 및 'yarn storybook' 명령어 실행 하도록 설정
- [ ] Vercel 국가 설정 korea 나 옵션이 없다면 Asia로
