### ISSUE TITLE
feat: Button/TextButton 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#12]
## 📌 작업 내용
아래 이미지에 있는 Text Button 컴포넌트 개발
 
![Image](https://github.com/user-attachments/assets/5e83ce06-b76b-427e-9086-dc38970a1ace)

## ✅ To-Do

- [ ] Button 폴더 내부에 TextButton 폴더 생성(Button/TextButton/)
- [ ] TextButton.tsx , TextButton.stories.ts, TextButton.style.ts 생성
- [ ] text를 props 로 전달받아서 문구가 잘 나오는지 확인
- [ ] onClick을 props로 전달받아서 문구가 잘 나오는지 확인(onClick의 경우 없을 수도 있다. onClick? ) 
- [ ] 스토리북에 위의 내용을 반영해서 잘 나오는지 확인

## 📝 참고사항

디자인은 생각했을 때 제일 간단한 부분만 적용해주세요.
(구현하는 사람에게 맡깁니다!) 
이후 디자인 시안 나오면 디자인 수정!

**Comment by JW-Ahn0** [comment]
디자인 작업 제가 맡았습니다.
