### ISSUE TITLE
feat: PostImageList 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#132]
## 📌 작업 내용

![Image](https://github.com/user-attachments/assets/0d556c1d-0a36-4c46-b34a-d543e81aace5)

### props

- onClick: (idx:number ) => void;
- imgUrls: string[];
- thumbnailIdx: number;

## ✅ To-Do

- [ ] imgUrls map으로 돌면서 PostImageItem 가 잘 나오는지 확인
- [ ] thumbnailIdx 값이 -1이라면 대표사진을 첫 번째 사진으로 지정하는지 확인 
- [ ] thumbnailIdx 값이 존재한다면 해당 idx 번째의 사진이 대표사진으로 지정되는지 확인 
- [ ] List 안에있는 Item에 X 버튼을 누르면 onClick 이벤트가 잘 실행되고, 파라미터의 idx 번호가 잘 출력 되는지 확인

### 선행 조건

- #31

**Comment by JW-Ahn0** [comment]
- #32 
PostImageManager 부분이 이미 존재해서 해당 이슈는 닫도록 하겠습니다.
