### ISSUE TITLE
fix: Build 오류 수정

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#156]
## 📌 작업 내용

Build 시 발생하는 오류들을 수정하겠습니다.

## ✅ To-Do

- [x] `IconButton` Type '"round" | "square"' is not assignable to type 'undefined'.
- [x] `ChatList` Module '"../ChatItem"' declares 'IChatItemProps' locally, but it is not exported.
- [x] `NeighborhoodAuthForm` 'useRef' is declared but its value is never read.
- [x] `PostImageManager` 'useEffect' is declared but its value is never read.
- [x] `PostImageManager` 'args' is declared but its value is never read.
