### ISSUE TITLE
feat: RouterGuard 생성

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#161]
## 📌 작업 내용

RouterGuard 생성하겠습니다.

## ✅ To-Do

- [ ] 권한(알림 권한)이 없는 사용자 앱 접근 막기 => **논의**
- [ ] 채팅방 접근 시 해당 채팅에 참여중인 사용자만 접근할 수 있게 (접근 시 404페이지)
    - success가 false면 처리 (페이지에서 직접??)
- [ ] 사용자가 로그인은 했는데 닉네임이 없다면 프로필 설정 페이지로 리다이렉트

## 선행 작업

- #160 
- #244

**Comment by ppyom** [comment]
# !! 일단 얘는 페이지 개발 끝나고 로그인 API 끝나고 진행!!

## 로그인 했을 때 접근 가능한 페이지

아래 저 두개 제외 모두

## 로그인 하지 않았을 때 접근 가능한 페이지

- #243 
- #244

**Comment by ppyom** [comment]
1. LoginRouter가 profile 조회
2. 500에러 발생하면 user 제거
3. 정상처리되면 user 저장 후 원래 페이지로 이동

**Comment by ppyom** [comment]
- 동네 수정 추가
