### ISSUE TITLE
feat: NeighborhoodSelectionTemplate 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#166]
## 📌 작업 내용

![Image](https://github.com/user-attachments/assets/68f855e6-bb22-4365-a9c0-c39140d953f2)

### props

- neighborhoods: Naighborhood[]
- onFindCurrentLocationClick: () => void

## ✅ To-Do

- [x] TopBar의 input 보여질 페이지에 해당 페이지 추가
- [x] props로 받은 근처 동네 목록이 정상적으로 출력되는지 확인
- [x] onFindCurrentLocationClick 함수가 정상적으로 실행되는지 확인

### 선행 조건

- #180 (코드 보고 따라하겠습니다.....)
- #12 
- #60 
- #50  (페이지에서)

**Comment by ppyom** [comment]
NaverMaps에 근처 동네를 목록으로 불러올 수 있는 기능이 없어 목록으로 하지 않고 현재 사용자 위치 동네와 검색으로만 리스트를 수정할 수 있게 변경 ㅠ..

이후 동네 목록 가져오는 부분은 논의 필요.....
