### ISSUE TITLE
feat: IconWithText  컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#17]
## 📌 작업 내용
![Image](https://github.com/user-attachments/assets/1e7a840c-a98a-46bf-aa51-0fae00d57535)
![Image](https://github.com/user-attachments/assets/6e436594-f4f2-495a-833c-61cf43932a19)

## props 

IconComponent : 아이콘 컴포넌트 
title : string
desc? : string 
onClick? : 함수
iconLocation? : "default" ,"right"  (기본값: default)

## ✅ To-Do

- [x]  IconWithText.tsx ,  IconWithText.stories.ts ,  IconWithText.style.ts 파일 생성
- [x] IconComponent 를 props로 받아 잘 출력되는 지 확인
- [x] title 을 props로 받아 잘 출력되는지 확인
- [x] desc이 존재하지 않는 경우는 마이페이지처럼, 존재하는 경우는 권한 설정 화면 처럼 나오도록 수정
- [x] onClick을 props로 전달받아서 문구가 잘 나오는지 확인
- [x] 스토리북에 위의 내용들을 반영해서 잘 나오는지 확인
- [ ] 컴파운드 패턴이 제대로 적용되었는지 확인
- [x] iconLocation이 "right" 인 경우 오른쪽에 위치 잘 되는지 확인

## 📝 참고사항

컴파운드 패턴 적용 필요.

**선행조건 : #8 , #29**

**Comment by JW-Ahn0** [comment]
컴파운드 패턴 부분이 TODO에 있어 해당 부분을 구현하기 전 
패턴을 적용한 것과 하지 않은 것에 대해 비교를 해볼려고 합니다.

컴파운드 패턴을 적용하지 않고 개발하는 경우의 장점
![Image](https://github.com/user-attachments/assets/5d791e20-3b49-43cd-9969-d27df379a26d)

- Storybook 에서 props에 대해서 컨트롤이 가능하다. (위의 props에 대해서 컨트롤이 가능합니다.)

단점
- 이후에 iconLocation와 같이 위치에 대해서 조작해야 하는 props가 지속적으로 추가된다면 전달받아야 하는 props의 개수가 많아져
유지보수가 복잡해진다는 단점이 있습니다.
현재는 아래 사진과 같이 order에서 iconLocation 값에 따라 순서를 바꿔주는 형태로 개발되어 있습니다.
 ![Image](https://github.com/user-attachments/assets/9934f9b9-8637-463b-a167-593fde293b8a)

**Comment by JW-Ahn0** [comment]
컴파운드 패턴을 적용하게 된다면 index.tsx 파일 내용이 많아져 복잡한 것처럼 보일 수 있지만
사실 구조적으로는 굉장히 단순합니다. 
IconWithText 의 경우는 3가지로 나뉘어 집니다.

1. children을 내보내기만 하는 IconWithText 
![Image](https://github.com/user-attachments/assets/dce16f72-e9a0-4b3b-9ff0-797368a9554c)

2. Content(제목) 과 desc(부가설명) 을 담당하는 Content 컴포넌트 (Text 2개가 하나의 container로 합쳐진 것 뿐입니다.)
![Image](https://github.com/user-attachments/assets/bc036394-1ee0-454c-b378-a1eaff84b144)

3. Icon을 내보내기만 하는 Icon
![Image](https://github.com/user-attachments/assets/2999e56a-37b7-4ddf-bb87-6c622e2343a8)

**Comment by JW-Ahn0** [comment]
컴파운드 패턴을 적용함으로써 얻는 장점은 아래와 같습니다.

- IconWithText가 props를 받는게 아니라 그 하위인 IconWithText.Icon , IconWithText.Content에 props를 전달하기 때문에 이 각각을 독립적으로 사용가능
- 기존 iconLocation 같은 props가 사라져서 styled 파일이 단순해짐 (위치의 경우 그냥  IconWithText.Icon과  IconWithText.Content의 위치를 바꿔주기만 하면 됩니다)

단점

- IconWithText 자체는 children 제외 아무런 props를 받지 않으므로 Storybook에서 children에 대해 props 조작을 할 수 있는 옵션을 못 찾겠습니다..

![Image](https://github.com/user-attachments/assets/8f60cb5b-b68d-4c70-b856-a07b1ab21b6d)

따라서 storybook 에서 control 할 수 있는 부분이 없다는 문제가 있습니다.
![Image](https://github.com/user-attachments/assets/50db98c0-6744-43c0-be64-2b644141363f)

**Comment by ppyom** [comment]
@JW-Ahn0 @y0unj1NoH 

스토리북에 컴파운드패턴 이런 느낌이면 될까요???

| No Desc | Has Desc |
| -- | -- |
| ![Image](https://github.com/user-attachments/assets/febe819a-c432-4fbf-804d-e722238dc73a) | ![Image](https://github.com/user-attachments/assets/240bab57-2601-4b7a-989f-6ee6579bbd39) |

Root가 아닌 **IconWithText.Icon, IconWithText.Content의 props를 받아서 처리**하도록 만들어봤습니다.....

**component가 필수 값이 아닌 optional**이라 아래처럼 작성해도 되는 듯 합니다.......!!

만약 **스토리로 나누어서 작업한다면 argTypes을 meta에 작성하지 말고 각각의 스토리에 작성**하는 방식으로 만들면 될 것 같습니다!

```tsx
// IconWithText_Compound/stories.tsx
import { Meta, StoryObj } from "@storybook/react";
import { IconWithText } from ".";
import { IconSizes } from "components/atoms/Icon/styled"; // 얘는 constants로 분리가 필요해보이네요......ㅠ 나중에 생각나면 하겠습니다....
import * as Icons from "components/atoms/Icon";

const meta: Meta<(typeof IconWithText)[keyof typeof IconWithText]> = {
  title: "Molecules/IconWithText_Compound",
  // component: IconWithText,
  tags: ["autodocs"],
  argTypes: {
    icon: {
      control: "select",
      options: Object.keys(Icons),
      mapping: Icons,
    },
    size: {
      control: "select",
      options: Object.keys(IconSizes),
    },
    content: {
      control: "text",
    },
    desc: {
      control: "text",
    },
  },
};

export default meta;

type Story = StoryObj<typeof meta>;

export const IconLeft: Story = {
  args: {
    icon: Icons.LocationIcon,
    size: "m",
    content: "위치",
  },
  render: (args) => {
    return (
      <IconWithText>
        <IconWithText.Icon icon={args.icon} size={args.size} />
        <IconWithText.Content content={args.content} desc={args.desc} />
      </IconWithText>
    );
  },
};

export const IconRight: Story = {
  args: {
    icon: Icons.LocationIcon,
    size: "m",
    content: "위치",
  },
  render: (args) => {
    return (
      <IconWithText>
        <IconWithText.Content content={args.content} desc={args.desc} />
        <IconWithText.Icon icon={args.icon} size={args.size} />
      </IconWithText>
    );
  },
};
```

```tsx
// IconWithText_Compound/index.tsx
import { IconType } from "types/icon";
import { IconWithTextContentWrapper, IconWithTextWrapper } from "./styled";
import { Text } from "components/atoms";

// IconWithText 기본 컴포넌트
export interface IIconWithTextProps {
  children?: React.ReactNode;
}

const IconWithTextRoot = ({ children }: IIconWithTextProps) => {
  return <IconWithTextWrapper>{children}</IconWithTextWrapper>;
};

// Content 컴포넌트
export interface IIconWithTextContentProps {
  /** Text 내용 */
  content: string;
  /** 부가설명 내용(권한 설정 화면) */
  desc?: string;
}

const Content = ({ content, desc }: IIconWithTextContentProps) => {
  return (
    <IconWithTextContentWrapper content={content}>
      <Text content={content} variant={"body1"}></Text>
      {desc && <Text content={desc} variant={"button"}></Text>}
    </IconWithTextContentWrapper>
  );
};

// Icon 컴포넌트
export interface IIconWithTextIconProps {
  /** 아이콘 컴포넌트 : atoms/Icon 경로 참조 */
  icon: IconType;
  /** 아이콘 사이즈 : s / m / l */
  size?: "s" | "m" | "l";
}

const Icon = ({ icon, size = "m" }: IIconWithTextIconProps) => {
  const IconComponent = icon;
  return <IconComponent size={size} />;
};

export const IconWithText: typeof IconWithTextRoot & {
  Icon: typeof Icon;
  Content: typeof Content;
} = Object.assign(IconWithTextRoot, {
  Icon,
  Content,
});
```
