### ISSUE TITLE
feat: Textarea 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#170]
## 📌 작업 내용

- Atom의 Textarea 컴포넌트의 기능 개발

- 라벨을 제외한 부분
![Image](https://github.com/user-attachments/assets/c3e344b4-a869-47df-bb24-357cf13e3467)
- 디자인 시안
![Image](https://github.com/user-attachments/assets/8c90388c-4373-4072-a7b0-480e755276a6)

### props
- id?: string
- placeholder?: string
- value: string
- setValue: React.Dispatch<React.SetStateAction<string>>

## ✅ To-Do

- [x]  props로 전달 받은 placeholder가 제대로 들어가는지
- [ ] props로 전달 받은 text가 제대로 들어가는지
- [x] onFocus 시 스타일이 변경되는지
