### ISSUE TITLE
feat: TabItem 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#19]
## 📌 작업 내용

![Image](https://github.com/user-attachments/assets/b82f0ec4-f88b-4d2f-bd67-2823e1dcf4bb)

## props
- state : "default" | "active"
- text : string

## ✅ To-Do

- [x] text 를 props로 받아서 값이 잘 출력되는지 확인
- [x] state 를 props로 받아서 active 상태일 때 색깔이 잘 변경되는지 확인
- [x] 스토리북에 위의 내용들을 반영해서 잘 나오는지 확인

## 📝 참고사항

없음
