### ISSUE TITLE
feat: ChatListTemplate 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#190]
## 📌 작업 내용

![Image](https://github.com/user-attachments/assets/d9574f82-99fd-49e1-844c-94178f6ad05d)

### props

  
  - menus: string[]; /** 탭 메뉴 title 리스트 */
  
  - onClick: (tab: string) => void; /** 탭 메뉴 클릭 이벤트 */
  
  - chatItems: IChatItemProps[]; /** 채팅 방 아이템 리스트 Organisms/ChatItem 컴포넌트 참조  */

## ✅ To-Do

- [ ] menus 가 상단의 탭 메뉴로 잘 나오는지 확인
- [ ] onClick 이벤트로 상단의 탭 메뉴 이름이 console.log에 출력이 잘 되는지 확인
- [ ] chatItems 로 ChatList 컴포넌트의 내용이 잘 출력 되는지 확인

### 선행 조건

- #56 
- #24
