### ISSUE TITLE
feat: Logo 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#2]
## 📌 작업 내용

미어켓 로고 컴포넌트 개발
![Image](https://github.com/user-attachments/assets/733aba5d-8b90-4528-9369-f7e51f39b156)

## ✅ To-Do

- [ ] Logo.tsx ,Logo.stories.ts , Logo.style.ts 파일 생성
- [ ] 스토리북에서 아무 이미지나 잘 나오는지 확인(.svg) 
- [ ] img 태그의 alt 부분은 "미어켓 로고"

## 📝 참고사항

실제 제작된 로고는 이후에 적용
그전까지는 아무 이미지 적용

1시간
