### ISSUE TITLE
feat: LabeledInput 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#20]
## 📌 작업 내용

- Molecule의 LabeledInput 컴포넌트 개발

![Image](https://github.com/user-attachments/assets/a9f80a27-a7e8-4a10-ab33-b6a9c3016e95)

### props
- label: string
- placeholder: string
- value: string
- onChange: function
- onClick: function

## ✅ To-Do

- [x] props로 전달 받은 label이 `<Label>`에 잘 반영되는지
- [x] `<Input>`의 onChange가 잘 반영되는지
- [x] `<Input>`의 onClick이 잘 반영되는지
