### ISSUE TITLE
fix: TopBar 수정

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#215]
## 📌 작업 내용

현재 TopBar를 사용했을 때 스타일링에 문제가 있는 것을 확인했습니다.

![image](https://github.com/user-attachments/assets/9813ce35-e221-4eef-b3c1-0fcfbe49d445)
(아주 이상한 title의 위치.,.....ㅠㅠ..)

그래서 해당 스타일을 간단하게 수정하려고 합니다.

## ✅ To-Do

- [x] 아무것도 없는 아이콘 상태로 사용될 NoIcon 컴포넌트 생성 (빈칸)
- [x] clear 할 때 title 제외 (clear 자체를 제외할지 확인 필요 ㅠㅠ..)
- [x] rightIcon 타입 설정할 때 한번에 설정할 수 있게 수정

**Comment by ppyom** [comment]
![image](https://github.com/user-attachments/assets/c5c86059-7074-4b43-8233-371578ae9f47)
ㅎㅎ..
