### ISSUE TITLE
feat: InputWithButton 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#22]
## 📌 작업 내용

- Molecule의 InputWithButton 컴포넌트 개발
- 상세페이지의 문의사항 댓글창 
![Image](https://github.com/user-attachments/assets/1b493731-c89f-4feb-bda6-a47df1ef786e)

### props
- onChange: function
- onClick: function
- placeholder:string
- text: string

## ✅ To-Do

- [x] `<Input>`의 onChange가 잘 작동하는지 
- [x] `<TextButton>`의 onClick이 잘 작동하는지 (클릭 작동시 console.log에  `<Input>`의 value 출력)
- [x] `<TextButton>`의 placeholder, text 전달 잘 되는지 확인
