### ISSUE TITLE
feat: HomePage 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#228]
## 📌 작업 내용

- HomeTemplate 기반으로 HomePage 컴포넌트 개발

## ✅ To-Do

- [ ] 중고 물품 조회 API로 물품 리스트 가져오기  (http://localhost:8080/api/v1/products)
- [ ] 물품 리스트 중 물품 클릭시  navigate(/product/:productId) 로 페이지 이동 
- [ ] '내 물품 판매하기' 버튼 클릭 시 navigate(/product) 로 페이지 이동 

### 선행 조건

- #185
