### ISSUE TITLE
feat: DetailPage 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#247]
## 📌 작업 내용

상세 페이지 화면

## ✅ To-Do

- [x] 화면 구성
- [x] API 코드 작성
- [x] 백엔드 연동

### 선행 조건

- #167

**Comment by ppyom** [comment]
#

**Comment by ppyom** [comment]
# 답글

## 작성

케밥메뉴의 답글이 눌린 댓글의 id 저장 후 댓글 작성 완료되면 해당 id를 parent로 전송

## 조회

답글인 경우 케밥메뉴의 답글 버튼 제외

## 출력

부모 댓글의 자식으로 출력

**Comment by ppyom** [comment]
# 내일 질문

1. product detail쪽에서 요청을 보낸 사용자에 따라 응답 데이터를 변경할 수 있나요? (예를들어 판매자가 자신의 글의 상세페이지에 접속하면 상품의 최고 가격을 보여주고, 구매자가 현재 내가 입찰한 글에 들어가면 내가 입찰한 가격을 보여주는 방식??!!) + 내가 올린 글인지 플래그??
    - 되지 않아도 상관은 X! 만약 userId를 클라이언트에서 관리할 수 없다면 플래그는 필요합니다... (내가 작성한 글에 따라 화면에서 다르게 보여야함)
2. 댓글 어떤식으로 진행되어야할지?? swagger.....!

**Comment by ppyom** [comment]
# 댓글 케밥

commentId 넘겨서

**Comment by ppyom** [comment]
# 남은 작업

- [ ] TopBar 케밥
- [ ] 백엔드 기능 연동

**Comment by ppyom** [comment]
# 남은 작업

- [ ] 디자인
- [ ] 입찰 기능 연동

**Comment by ppyom** [comment]
- 댓글 이미지 적용 `profileIamge`
- 판매자 정보 수정

**Comment by ppyom** [comment]
댓글 케밥 z-index 올리기..............

**Comment by ppyom** [comment]
TopBar 케밥메뉴 위치 이동

**Comment by ppyom** [comment]
가격 replace `Number(formData.minimumPrice!.replace(/,/g, ""))`로 수정

**Comment by ppyom** [comment]
거래 희망 장소 위치 보내기

**Comment by ppyom** [comment]
# 조기마감 적용 이후

 productRefetch() 적용

**Comment by ppyom** [comment]
# 삭제 눌렀을 때 모달

**Comment by ppyom** [comment]
삭제된 게시글 보고있는 경우 404말고 홈으로 이동

**Comment by ppyom** [comment]
채팅 댓글 달 때 이미지 null인 경우 깨져서 default 이미지 넣어주실 숭 ㅣㅆ을까요?

**Comment by ppyom** [comment]
조기종료 진행 중 가격 낮게 수정

**Comment by ppyom** [comment]
댓글 수정 완료하면 "수정되었습니다." 토스트

**Comment by ppyom** [comment]
입찰자 없는 경우 버튼 입찰자 없습니다

**Comment by ppyom** [comment]
마감된 경우 AuctionControlBar 제거
