### ISSUE TITLE
feat: RoundImageWithText 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#25]
## 📌 작업 내용

CategoryGrid에서 사용될 RoundImageWithText입니다.

![Image](https://github.com/user-attachments/assets/3161431c-78dc-4acd-a9ad-d72beb54c447)

### props

- imageUrl: string
- title: string
- onClick: 함수

## ✅ To-Do

- [x] imageUrl에 아무거나 이미지를 넣었을 때 정상적으로 출력되는지 확인
- [x] text에 입력된 텍스트가 name에 출력되는지 확인
- [x] onClick 이벤트가 정상적으로 실행되는지 콘솔에서 확인

### 먼저 진행되어야 할 작업

- #3 
- #9

**Comment by ppyom** [comment]
![Image](https://github.com/user-attachments/assets/5d0f5c37-609e-4e62-8730-4f45a32db5c1)
