### ISSUE TITLE
feat: TextWithImage 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#26]
## 📌 작업 내용

![Image](https://github.com/user-attachments/assets/029ead2a-fa21-4667-8f13-40836f59ba1c)

##props

- title : string
- desc : string
- imgUrl : string

## ✅ To-Do

- [ ] title를 props로 받아서 타이틀이 잘 나오는지 확인
- [ ] desc를 props로 받아서 설명이 잘 나오는지 확인
- [ ] desc의 경우 정해진 화면을 벗어나면 "..." 으로 잘 나오는지 확인
- [ ] imgUrl을 props로 받아서 img가 잘 나오는지 확인
- [ ] 스토리북에 위의 내용들을 반영해서 잘 나오는지 확인

## 📝 참고사항

이미지의 경우 개발하는 사람이 임의로 설정한 이미지 URL 사용해도 무방

**Comment by ppyom** [comment]
# css 수정

- justify-content: space-between
- .text-con에 flex: 1
- ImageWrapper에 max-width 80px
