### ISSUE TITLE
feat: Text 공통 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#3]
## 📌 작업 내용
텍스트의 경우 style을 props(클래스 명)으로 전달 받아 변경

![Image](https://github.com/user-attachments/assets/bae3aea1-0b3a-4e4c-b9fa-c11c3f1041a6)

## ✅ To-Do

- [ ] Text.tsx, Text.stories.ts , Text.style.ts 파일 생성
- [ ] 예시 style 4가지 정도만 추가 해놓기 (H1,  subtitle1, Button, H4) (너무 많으면 이후 작업이 많아짐) 
(4가지 타입은 만드는 사람에게 맡기겠음) 
- [ ] 기본은 p 태그로 작업
- [ ]  스토리북에서 타입 별로 잘 표시되는지 확인

## 📝 참고사항

실제 텍스트 스타일의 경우 디자인 시안이 완성됬을 때 추가 예정

1시간

**Comment by JW-Ahn0** [comment]
디자인 제가 맡겠습니다.
