### ISSUE TITLE
feat: UploadedImageCounter 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#30]
## 📌 작업 내용

- 상세 페이지에서 사진 등록 및 등록된 사진 개수
![Image](https://github.com/user-attachments/assets/6a6f350f-a58c-4438-aadb-96aed44daac1)

### props
- text: string
- currentCount: number
- totalCount?: number
- onChange : function

## ✅ To-Do

- [x] ImageUpload 컴포넌트에 onChange를 전달
- [x]  이미지가 등록되면 사진 등록의 카운트가 제대로 반영되는지
- [x]  이미지 업로드 컴포넌트가 추가되었는지 확인

## 📝 참고사항

- totalCount는 아무 값이나 괜찮음

### 선행 조건
- #6
