### ISSUE TITLE
feat: AuctionTimer 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#34]
## 📌 작업 내용

- 경매 마감 기한까지의 남은 시간을 타이머 형식으로 보여줍니다.

![Image](https://github.com/user-attachments/assets/d7b71ff4-e630-4e98-b393-a53abc167199)

### props

- expiredTime: String

## ✅ To-Do

- [x] props로 전달 받은 time이 남은 시간으로 잘 계산되어 반영되는지
- [x] 시간 경과에 따라 제대로 업데이트되는지
- [x] util 함수를 사용해서 내부에서 해당 마감시간 타이머 돌리는 방식으로 구현 (format 함수 남은시간 02:00:00)

## 📝 참고사항

- 실시간으로 계속 렌더링 되는 부분인데, 이런 게 성능 부하에 영향을 줄 수 있을까요?
- sec도 같이 보여지도록

### 선행 조건
- #3 
- #68

**Comment by ppyom** [comment]
디자인 수정하겠습니다.

#247
