### ISSUE TITLE
feat: 판매내역 API 연동

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#347]
## 📌 작업 내용

~~구매내역~~ 판매내역 API 연동

## ✅ To-Do

- [x] api 호출 로직 작성
- [x] 화면에 데이터 출력

**Comment by ppyom** [comment]
# 남은 내역

- [ ] API 제대로 동작하는지 확인
    - [ ] productId 보내지지 않는다면 index 사용해서 수정
- [ ] Empty Template 적용
- [ ] 남은시간 over로 나오는거 수정?? => 거래완료에서 제거하면 되는거 아닌가????

**Comment by ppyom** [comment]
Empty Template를 적용하기엔 대공사가 필요해 보여 일단 보류
