### ISSUE TITLE
feat: Profile 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#35]
## 📌 작업 내용

- 유저의 프로필로 프로필 사진, 유저 닉네임, 위치를 확인할 수 있습니다.

![Image](https://github.com/user-attachments/assets/9b77b629-8184-4d09-9ca7-5a8808ce2ac4)

### props

- imgUrl: string
- nickname: string
- location: string

## ✅ To-Do

- [ ] props로 전달 받은 imgUrl가 제대로 반영되는지
- [ ] props로 전달 받은 nickname이 제대로 반영되는지
- [x] props로 전달 받은 location이 제대로 반영되는지

## 📝 참고사항

- 고도화에서 온도가 추가될 예정입니다.

### 선행 조건
- #3
- #9
