### ISSUE TITLE
feat: 채팅방 API 거래 완료 여부 추가

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#358]
## 📌 작업 내용

- 거래 완료 여부를 알 수 있도록 예찬님과 논의 후에 적용이 필요합니다.
![image](https://github.com/user-attachments/assets/7222e17d-9335-4665-acbe-84375fa10dd8)

## ✅ To-Do

- [ ] 채팅방 입장 api 연동 수정
- [ ] 버튼 disabled 처리 (거래 완료 시 `거래가 완료되었어요!` 텍스트와 disabled 변경 필요)
  - [ ] 거래 완료 버튼 눌렀을 때의 처리도 필요

**Comment by y0unj1NoH** [comment]
백엔드 api는 완료되어서, 바로 작업이 가능하십니다..!!
