### ISSUE TITLE
feat: ItemDetails 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#36]
## 📌 작업 내용

- 상세페이지의 물품에 대한 상세 정보로 거래 완료 배지, title, category, createdAt(게시글 생성 시간), description을 포함합니다.

![Image](https://github.com/user-attachments/assets/ba2c26f1-e927-437d-a8f8-20f8bc743cd9)

### props
- isDoneDeal: boolean
- title: string
- category: string
- location: string => description
- createdAt: string

## ✅ To-Do

- [x] props로 전달 받은 isDoneDeal이 true일 시 `<Badge>`가 잘 반영되는지
- [x] props로 전달 받은 title이 제대로 반영되는지
- [x] props로 전달 받은 category가 제대로  반영되는지
- [x] props로 전달 받은 ~location~ description이 제대로  반영되는지
- [x] props로 전달 받은 createdAt이 현재 시간으로 기점으로 잘 계산되어 반영되는지(유틸함수 사용)

## 📝 참고사항

- ~`<Badge>`의 유무에 따라 구조가 바껴 **Compound pattern**으로 구현합니다.~ 컴파운드 X Props로!!
- isDoneDeal 값이 false 인 경우 `<Badge>` 가 없어야함

### 선행 조건

- #3  
- #11 
- #29 
- #68

**Comment by ppyom** [comment]
디자인 수정하겠습니다.

#247
