### ISSUE TITLE
feat: LocationMap 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#37]
## 📌 작업 내용

- 상세 페이지의 거래 희망 장소 관련 섹션입니다. 해당 섹션을 클릭하면 `거래 희망 장소`페이지로 리다이렉트됩니다.

![Image](https://github.com/user-attachments/assets/6da6b83f-2488-41fa-8d6f-5679cf885684)

### props

- location: string
- latitude: number
- longitude: number
- onLocationMapClick: function

## ✅ To-Do

- [x] props로 전달 받은 location이 제대로 반영되는지 (ex) 보라매공원 CU)
- [x] props로 전달 받은 latitude, longitude가 `<Map>`에 제대로 반영되는지
- [x] 클릭 이벤트 시 콘솔에 위도, 경도가 출력 되는지

## 📝 참고사항

- 생각해보니 거래 희망 장소 페이지가..?! 없어서, 아토믹 패턴에 추가했습니다!
- latitude, longitude로 불러오게 했는데 객체로 받아오는 게 더 좋을 것 같습니다. 이름은 같이 고민... coord..?

### 선행 조건

- #3 
- #55

**Comment by y0unj1NoH** [comment]
TODO에 **클릭 이벤트 시 콘솔에 위도, 경도가 출력 되는지**로 적었는데, 
단순하게 "LocationMap 클릭!"을 출력하는 것으로 변경하여 테스트하였습니다.

**Comment by ppyom** [comment]
디자인 수정하겠습니다.

#247
