### ISSUE TITLE
feat: CommentItem 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#38]
## 📌 작업 내용

- 상세페이지의 문의사항 섹션에 들어가는 CommentItem입니다.
- 프로필 사진, 댓글 작성자 닉네임, createAt(댓글 생성 시간), content(댓글 내용), 케밥 메뉴가 포함됩니다.
- 케밥 메뉴는 댓글 관련 기능들이 포함되며, 아래와 같이 구성됩니다.
    - 댓글 작성자
        - 답글
        - 수정
        - 삭제
    - 일반 유저
        - 답글
        - 신고하기
        - 차단하기

![Image](https://github.com/user-attachments/assets/6c77202e-dcf8-41a9-885c-fb9dadeac2b9)

- 케밥 메뉴
![Image](https://github.com/user-attachments/assets/cf500f8b-27ff-472b-bb22-1203c5197185)

### props

- commentId: number
- imgUrl: string
- nickname: string
- createdAt: string
- content: string
- isMyComment : boolean

## ✅ To-Do

- [x] props로 전달 받은 imgUrl이 반영되는지
- [x] props로 전달 받은 nickname이 반영되는지
- [x] props로 전달 받은 createdAt이 반영되는지 (createdAt은 Util 함수의 n시간 전 나타내는 함수 사용)
- [x] props로 전달 받은 content가 반영되는지
- [x] 케밥 메뉴를 클릭했을 때, 각각 메뉴의 이름과 commentId가 콘솔에 출력 되는지 
- [x] isMyComment 값에 따라 케밥메뉴 나오는 개수가 다르게 구성 (true인 경우 댓글 작성자, 아닌 경우 일반 유저)
- [x] 케밥 메뉴 구성할때는 임의의 onClick 이 컴포넌트가 생성해서 전달해주는 것으로(console.log()찍히는 onClick)

## 📝 참고사항

- 케밥 버튼에서 어떤 값을 클릭 시 그것에 대한 commentId와 실행해야 하는 기능을 전역 상태로 넘겨주어 page에서 처리하는 느낌..? 뭐가 좋을지....요.... 데이터 조작과 관련된 컴포넌트에 대해서 머리가 안굴러가,,는,,,  (이 부분은 보류)

### 선행 조건

- #3
- #9 
- #15 
- #28
- #68

**Comment by ppyom** [comment]
디자인 #263
