### ISSUE TITLE
feat: Comment 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#39]
## 📌 작업 내용

- 상세페이지의 댓글을 관리하는 섹션입니다.
- 문의사항 title과 댓글, 댓글 작성란이 포함됩니다.

![Image](https://github.com/user-attachments/assets/71849ce1-f9c4-4e16-9064-cdf20f3c7ec7)

### props
- Comments : Comment[] (= Comment 타입은 참고사항 확인 )

## ✅ To-Do

- [x] "문의사항" type:string 이랑 text:string 를 전달해준다. 
- [x] placeholder:string , text: string를 InputWithButton onChange: function , onClick: function 에 전달해준다.  (function 의 경우 콘솔에 찍히게만)
- [x] Comments 를 map으로 돌면서 CommentItem 컴포넌트를 생성한다.

## 📝 참고사항
Comment : {
commentId: number
imgUrl: string
nickname: string
createdAt: string
content: string
isMyComment : boolean
}

- 댓글이 없을 시, "아직 댓글이 없어요. 가장 먼저 댓글을 남겨보세요."가 보이는 게 좋을 것 같습니다. (=일단 보류)

### 선행 조건

- #3 
- #22
- #38

**Comment by ppyom** [comment]
디자인 #263
