### ISSUE TITLE
feat: BottomNavBar 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#41]
## 📌 작업 내용

BottomNavBar 컴포넌트

![Image](https://github.com/user-attachments/assets/1cb3239d-0fe5-47f3-b0af-47c5b43dc8d4)

### props

- X 

### 각 메뉴의 pathname (임의)

- 홈: "/"
- 시세조회: "/history" (판매내역느낌??)
- 채팅: "/chat"
- My: "/my-page"

## ✅ To-Do

- [x] NavBarItem
    - [x] `type`을 `state`로 변경
    - [x] title: 각 메뉴의 이름
    - [x] onClick: `console.log(해당메뉴pathname)`
    - [x] ~type~ state: 현재 path가 해당 메뉴의 path라면 NavBarItem type을 "active"로 설정 (아닐 경우에는 "default")
- [x] title에 입력한 메뉴 이름이 정상적으로 반영되는지 확인
- [x] NavBarItem 클릭 시 현재 path가 출력되는지 확인
- [x] 현재 path에 해당하는 NavBarItem이 active 스타일인지 확인
- [x] Icon 컴포넌트 설정해서 NavBarItem 넘겨주기 (여기서 만드는 거) 

## 📝 참고사항

Router를 연결하지 않았기 때문에 navigate(pathname)부분은 console.log(pathname) 사용!!

### 선행 조건

- #18

**Comment by ppyom** [comment]
디자인 적용 이예진
