### ISSUE TITLE
feat: Header 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#47]
## 📌 작업 내용

Header 컴포넌트

| Home | Default |
| -- | -- |
| ![Image](https://github.com/user-attachments/assets/24b5af5a-b30f-4c1e-9b43-09f5e269a5fa) | ![Image](https://github.com/user-attachments/assets/5fdaaf77-f615-418c-9dbf-de51116d5c08) |
| Title 출력 시 IconWithText(iconLocation = right) | Text |

### props

- type: "default" | "home"
- title: string

## ✅ To-Do

- [x] 각 type에 따른 형태가 정상적으로 출력되는지 확인
- [x] title에 입력 된 텍스트가 정상적으로 반영되는지 확인
- [x] 아래 화살표 아이콘 클릭 시 console에 "내 동네 선택" 출력되는지 확인
- [x] 검색 아이콘 클릭 시 console에 "/search" 출력되는지 확인
- [x] 종 아이콘 클릭 시 console에 "/notification" 출력되는지 확인

## 📝 참고사항

Router를 연결하지 않았기 때문에 navigate(pathname)부분은 console.log(pathname) 사용!!

### 선행 조건

- #3 
- #15 
- #17

**Comment by ppyom** [comment]
디자인 적용 이예진
