### ISSUE TITLE
feat: NeighborhoodAuthForm 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#48]
## 📌 작업 내용

동네 인증 폼 컴포넌트 개발
Map 컴포넌트 존재
Text 컴포넌트 존재
Button/TextButton 컴포넌트 존재

![Image](https://github.com/user-attachments/assets/cafd58a4-a087-4565-b09d-903efa3c9a0e)

### props

- isLocationExist : boolean  (현재 위치를 읽을 수 있는지 여부)
- locationName? : string  (현재 위치한 동이름)
- latitude? : postion? (위도,경도 타입) **(지도 컴포넌트 확정 후 수정)**
- longitude?  : postion? (위도,경도 타입) **(지도 컴포넌트 확정 후 수정)**
- onClick? : function  (동네인증 완료하기 onClick)

## ✅ To-Do

- [ ] isLocationExist 값에 따라 가운데 text의 내용이 바뀌는 지 확인
(isLocationExist===true인 경우, "현재 위치가 내 동네를 설정한 ${locationName} 에 있어요.
(isLocationExist===false인 경우,  "현재 위치 정보를 가져올 수 없어요!  잠시 후 다시 시도하거나 위치 정보를 허용해주세요!" )
- [ ] "동네인증 완료하기" 생성하여 TextButton에 전달하고 있는지 확인
- [ ] props로 받은 onClick 을 '동네인증 완료하기' TextButton에 전달하고 있는지 확인
- [ ] isLocationExist 가 true인 경우 latitude,longitude 지도 컴포넌트에 전달하고 있는지 확인

## 📝 참고사항

Map 하는 사람이 작업할 것.

### 선행 조건

- #55
- #12 
- #3
