### ISSUE TITLE
feat: Input 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#5]
## 📌 작업 내용

- Atom의 Input 컴포넌트의 기능 개발
- 기본 Input
![Image](https://github.com/user-attachments/assets/6a4a225c-2fd3-4b94-9b1e-df877f9abd6b)

- 클릭이 되는 Input
![Image](https://github.com/user-attachments/assets/360730ce-7037-421d-90c2-18b861570572)

## ✅ To-Do

- [x] props로 전달받은 placeholder가 제대로 들어가는지
- [x] props로 전달받은 text가 제대로 들어가는지
- [x] props로 전달 받은 onClick?이 제대로 수행이 되는지 (거래 희망 장소의 경우 onClick 이벤트 활성화) (클릭 하면 스토리북 상에서 문구 변경)
- [x] onClick이 존재한 경우 onChange 이벤트 prevent 필요

## 📝 참고사항

value만 넣었을 때 개발자 도구 상에서 오류 발생하는 지 확인 필요.

2시간
