### ISSUE TITLE
feat: TopBar 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#50]
## 📌 작업 내용

TopBar 컴포넌트

| Default | Search |
| -- | -- |
| ![Image](https://github.com/user-attachments/assets/5063bc5e-e7aa-4af9-a8e5-8740d9bb7f2e) | ![Image](https://github.com/user-attachments/assets/4c38b430-5a0d-489a-ad0f-264e2f0befaa) |
|  | Search 타입은 Text 대신 Input이 들어감 |

- leftIcon은 `←` 아이콘 고정
- rightIcon은 외부에서 받아서 사용 (optional)
- 클릭 이벤트도 외부에서 받아서 사용 (left는 필수 right는 옵션)

컴파운드 패턴으로 구현시
1.  왼쪽 IconButton
2. 중앙 Text
3. 오른쪽 IconButton
4. 중앙 Input 

### props

- onLeftIconClick: function  (해당 props 는 없는 것, 그냥 icon 컴포넌트에 onClick과 동일) 
- rightIcon?: Icon
- onRightIconClick?: function (해당 props 는 없는 것, 그냥 icon 컴포넌트에 onClick과 동일) 

#### TopBar.Default

- title: string

#### TopBar.Search

외부에서 State로 관리 => 어떻게 관리할지 이후 고민 필요

- value: string
- setValue: (value: string) => void

## ✅ To-Do

- [x] 각 타입의 형태가 정상적으로 출력되는지 확인
- [x] leftIcon 클릭 시 onClick 이벤트가 잘 작동하는지 확인 (console)
- [x] rightIcon 아무거나 넣은 후 잘 적용되는지 확인
    - [x] rightIcon 클릭 시 onClick 이벤트가 잘 작동하는지 확인 (console)
- [x] `TopBar.Default` title에 입력한 텍스트가 정상적으로 반영되는지 확인
- [x] `TopBar.Search` Input에 입력하면 value값이 변경되는지 확인

## 📝 참고사항

- 컴파운드 패턴 적용!!

### 선행 조건

- #29 
- #8 
- #3 
- #5

**Comment by ppyom** [comment]
# TopBar!!

- TopBar는 Header, BottomNavBar가 없는 모든 페이지에서 사용!!!
- 뒤로가기 버튼은 필수!! (path를 변경하는 버튼!!)
- Right 버튼은 선택!! (click event)
- 사용하는 위치에 따라 content만 Text | Input

## 컴파운드 적용

### 어떻게 사용될까???

```tsx
<TopBar>
  <TopBar.BackIcon /> {/* LeftIcon은 필수!! (BackIcon으로 고정) */}
  <TopBar.Title /> {/* 또는 TopBar.Input */}
  <TopBar.Icon /> {/* RightIcon은 선택!! */}
</TopBar>
```

- right에 Icon이 여러개 들어오는 경우????
  - 일단 생각 X, 지금은 들어온다해도 하나만!!

### 어떻게 만들까?

```tsx
// 1. TopBar(Root)
<TopBarWrapper>
  <TopBar.BackIcon icon={BackIcon} onClick={onBackClick} />
  {children}
</TopBarWrapper>

// 2. TopBar.BackIcon
// onBackClick
<IconButton icon={BackIcon} onClick={onBackClick} />

// 3. TopBar.Icon
// icon, onIconClick
<IconButton icon={icon} onClick={onIconClick} />

// 4. TopBar.Title => atoms/Text
// title
<Text content={title} />

// 5. TopBar.Input
// placeholder, value, setValue
<Input value={value} setValue={setValue} placeholder={placeholder} />
```

## 컴파운드 사용 X

### 어떻게 적용할까?

```tsx
<TopBar
    type="default" // "search"
    title={title}
    value={value}
    setValue={setValue}
    placeholder="placeholder"
    onBackIconClick={handleBackIconClick}
    rightIcon={icon}
    onRightIconClick={handleRightIconClick} />
```

### 어떻게 만들까?

```tsx
<TopBarWrapper>
    <IconButton icon={BackIcon} onClick={onBackClick} />
    {type === "default" 
     ? <Text content={title} />
      : <Input value={value} setValue={setValue} placeholder={placeholder} />}
    {rightIcon && <IconButton icon={icon} onClick={onIconClick} />}
</TopBarWrapper>
```

## 내 생각

- 레이아웃 컴포넌트에 하나만 두고 사용한다면 어떻게 만들어도 크게 상관 없음
- 각각의 컴포넌트에 만든다면 합친거 절대 X (컴파운드 무조건 적용하기!!)
- 컴파운드로 사용한다면 규칙만 지킨다면 상관없을듯!!

## 결론

일단 컴파운드로 만들기!!

**Comment by ppyom** [comment]
# 어떻게 해야할까!!!!!!!!

| Left | Content | (Right) |
|:--|:--:|--:|

flex + justify-content between => 2개인 경우에 조금 이상.......

일단 Grid로 해보기!!

**Comment by ppyom** [comment]
# Emotion/Styled 중첩 Select 관련

## 문제 상황

내부에서 사용되는 Input을 Selector 방식으로 불러와 사용하기 위해 아래와 같은 코드를 작성

```tsx
export const TopBarWrapper: ReturnType<typeof styled.div> = styled.div`
  display: flex;
  justify-content: center;
  padding: 1rem 0;
  background-color: #e9e9e9;
  position: relative;
  & > ${InputWrapper} {
    flex: 1;
    margin: 0 4.5rem;
  }
`;
```

스토리북에서 오류 발생

```
Error: Component selectors can only be used in conjunction with @emotion/babel-plugin, the swc Emotion plugin, or another Emotion-aware compiler transform.
```

## 원인 분석

react-swc에서 Component Selector 코드를 변환하지 못해서 발생한 오류??

## 해결 방법

Component Selector코드를 변환할 수 있게 플러그인 사용

1. `@swc/plugin-emotion` 설치
2. `vite.config.ts` -> plugins -> react에 `{ plugins: [["@swc/plugin-emotion", {}]] }` 추가

[참고 글](https://github.com/vercel/next.js/issues/30804)

**Comment by ppyom** [comment]
디자인 적용 이예진
