### ISSUE TITLE
feat: BlockedUserItem 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#51]
## 📌 작업 내용

차단 사용자 관리에서 하나의 아이템 의미
![Image](https://github.com/user-attachments/assets/3ee2f98f-b901-42ca-bc71-86438efab123)

### props

- Profile : {
imgUrl: string
userName: string
location: string
isBlocked : boolean
}
onClick?: function

## ✅ To-Do

- [x] props로 전달받은 Profile이 Profile 컴포넌트에 전달 잘 되는지 확인
- [x] props로 전달받은 onClick이 TextButton에 잘 전달되는지 확인
- [x]  "차단해제" text 생성해서 TextButton에 전달
- [x] isBlocked 의 내용에 따라 "차단하기", "차단해제" 로 변경

### 선행 조건

- #35 
- #12
