### ISSUE TITLE
feat: ChatItem 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#53]
## 📌 작업 내용

채팅 목록의 챗 아이템

![Image](https://github.com/user-attachments/assets/62f1faeb-07d2-429a-a49a-9e2d7433c7b5)

### props

- profileImgUrl : string
- itemImgUrl:string
- name : string
- lastMsg : string
- lastMsgTime : string
- lastMsgCnt : number 

## ✅ To-Do

- [x] props로 전달 받은 profileImgUrl, itemImgUrl 이 Overlapping Image 컴포넌트에 전달 잘 되는지 확인 (Image 컴포넌트의 타입은 "square")
- [x] props로 전달 받은 name이  Text 컴포넌트에 전달 잘 되는지 확인. (username 부분 )
- [x] props로 전달 받은 lastMsg이 Text 컴포넌트에 전달 잘 되는지 확인. (last message부분) (말 줄임은 여기서 처리)
- [x] props로 전달 받은 lastMsgTime이  Text 컴포넌트에 전달 잘 되는지 확인. (lastMsgTime은 "n 시간 전" 유틸 함수  사용)
- [x] props로 전달 받은 lastMsgCnt을 toString 먹여서 Badge 컴포넌트에 전달 잘 되는지 확인.("1" 부분)
- [x] lastMsgCnt 의 경우 0인 경우 Badge 컴포넌트 표출 X 

### 선행 조건

- #70 
- #3 
- #11 
- #68
