### ISSUE TITLE
feat: Modal 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#54]
## 📌 작업 내용

Modal 컴포넌트

| Alert | Confirm | Dialog | CustomButton |
| -- | -- | -- | -- |
| ![Image](https://github.com/user-attachments/assets/ae32e00f-a900-488f-8ed5-8bf67fdf7d26) | ![Image](https://github.com/user-attachments/assets/45731c55-6022-4806-9abf-9fbd79a7ce82) | ![Image](https://github.com/user-attachments/assets/e5cded31-55cc-4310-8f35-cd608caba115) | ![Image](https://github.com/user-attachments/assets/99059d2e-2568-4270-a09c-b30dc24dc5ff) |
|  |  | Input 사용 |  |

컴파운드 패턴으로 구현시 가이드(만드는 사람이 편한 방법으로 구현 권장)

1. X 추가로들어가고 , Text 존재하는 단순 모달(확인 버튼 같은거 없습니다.)
2. 가로 또는 세로로 나열되는 Button 컨테이너 존재 (type으로 세로, 가로 변경 가능하게)
3. 2의 컨테이너 안에 들어가는  Button. (여러개 들어갈수 있음)

### props

- text: string
- textAlign: "center" | "left" | "right"

#### Alert

- buttonText?: string (default: "확인")
- onButtonClick?: () => void

#### Confirm

- onOkButtonClick: () => void
- okButtonText?: string (default: "예")
- cancelButtonText?: string (default: "취소")
- onCancelButtonClick?: () => void

#### Dialog

- onOkButtonClick: () => void
- okButtonText?: string (default: "예")
- cancelButtonText?: string (default: "취소")
- onCancelButtonClick?: () => void
- value: string
- setValue: (value: string) => void

#### CustomButton

- buttons: { title: string; onClick: () => void }[]

## ✅ To-Do

- [ ] 입력한 text가 제대로 반영되는지 확인
- [ ] X 표시가 들어가서 해당 버튼 누르면 모달이 꺼지는 지
- [ ] 바깥 화면을 누르면 모달이 꺼지면 안됨. 이 부분 확인
- [ ] `Alert`
    - [ ] buttonText 입력 시 제대로 반영되는지 확인
    - [ ] onButtonClick 제대로 실행되는지 확인 (console)
- [ ] `Confirm`
    - [ ] okButtonText 입력 시 제대로 반영되는지 확인
    - [ ] onOkButtonClick 제대로 실행되는지 확인 (console)
    - [ ] cancelButtonText 입력 시 제대로 반영되는지 확인
    - [ ] onCancelButtonClick 제대로 실행되는지 확인 (console)
- [ ] `Dialog`
    - [ ] okButtonText 입력 시 제대로 반영되는지 확인
    - [ ] onOkButtonClick 제대로 실행되는지 확인 (console)
    - [ ] cancelButtonText 입력 시 제대로 반영되는지 확인
    - [ ] onCancelButtonClick 제대로 실행되는지 확인 (console)
    - [ ] Input에 입력하면 value에 재대로 반영되는지 확인
- [ ] `CustomButton`
    - [ ] 임의로 buttons에 2~3개정도 넣어보고 버튼 타이틀과 onClick이벤트가 정상적으로 실행되는지 확인
 

## 📝 참고사항

- 컴파운드 패턴 적용!!

### 선행 조건

- #29 
- #3 
- #12 
- #5

**Comment by ppyom** [comment]
# Modal 어떻게 만들지?

- 일단 ContextAPI 사용!!!! (약간 닫기 받은거 다른 컴포넌트로 넘기기 느낌으로 사용할 수 있을 것 같아 일단 사용!!!)
- 최대한 다른 UI 라이브러리들 참고하면서 만들기
- Storybook에서 어떻게 만들지가 고민....ㅠ

## 컴포넌트

### Modal(Root, Context)

Modal을 사용할 때 사용될 모든것을 담는곳 (Root)

#### props

- onClose: () => void
- placement?: "top" | "center" | "bottom" **( default: "center" )**

### Modal.BG

Modal 배경

### Modal.Content

실제 Modal이 될 Container

#### props

- children: React.ReactNode
- size?: "s" | "m" | "l" **( default: "m" )**

### Modal.Header

Header영역

#### props

- title?: string
- hasCloseButton?: boolean

### Modal.Content

Modal ContentText

### props

- text: string
- align?: "left" | "center" | "right" **( default: "left" )**

### Modal.ButtonContainer

Modal에서 사용될 버튼을 담는 Container

#### props

- buttons: { title: string; onClick: () => void }[]
- direction: "horizontal" | "vertical" **( default: "horizontal" )**

**Comment by ppyom** [comment]
# Modal을 호출한다면 어디에서??????

Modal 컴포넌트를 일단 우당탕탕 만들고나서 호출이 필요하다면 그 때에는 어디에서 호출해야할까?????

컴파운드 패턴으로 사용할 부분에 가져가서 사용한다면 과연 예쁘게 사용할 수 있을까????

## 결론

**컴파운드패턴으로 Modal 모양만 만들어두고 실제 사용되는 Modal 컴포넌트는 각각 만들기!!!!**

**Comment by ppyom** [comment]
# 화면에 보여질 때 어떻게 보여질까!!!!!

버튼 클릭하면 나오게 만들건데 어떻게 보여줄 수 있을까!!!!

**Comment by ppyom** [comment]
# 버튼 깨짐

![Image](https://github.com/user-attachments/assets/d2ba1795-f37d-47b3-aaad-359184397710)

테스트 디바이스 중 Small mobile(320px)에서 버튼이 3개 이상일 때 깨지는 현상 확인

![Image](https://github.com/user-attachments/assets/17600ec6-b3bf-4898-ad1b-e58ba868a8da)

임시로 `flex-wrap: wrap;` 설정 ㅠ

**Comment by ppyom** [comment]
# 전체적인 형태!!

![Image](https://github.com/user-attachments/assets/b0981ecd-74f5-44a8-be09-85f313b5273a)

```tsx
<Modal>
  <Modal.Background />
  <Modal.Container>
    <Modal.Header />
    <Modal.Body>
      { Body에 들어가는 내용들 }
    </Modal.Body>
    <Modal.ButtonContainer />
  </Modal.Container>
</Modal>
```

**Comment by ppyom** [comment]
# 멘토님 리뷰 적용

> 직접 공통 컴포넌트를 구축하시는만큼 접근성이나 가독성등에 조금 더 신경을 써주면 더 좋은 컴포넌트가 될거같습니다
예를들어 role="dialog" 등의 속성등이 예가 될수있을거같습니다

- [x] 일단 role 뭔지 몰라서 주석으로 구분 ㅠㅠ..

---

> 또한 모달같은 경우 보통 createPortal를 사용해 DOM의 최상단으로 보내는게 z-index 관리나 부모 스타일로부터 영향받지 않음등의 이점을 얻을 수 있습니다..! 이부분도 한번 고려해봐주세요!

> 현재 css로 모달 열고 닫고를 컨트롤 중이신데, 혹시 특별한 요구사항이 있을까요?
> 아니라면 닫을때 언마운트시키는게 메모리적으로 효율적일거같습니다

- [ ] 모달 관리하는 컴포넌트 구현!!

## `ModalContext` onClose 초기값을 null로 설정

> onClose 초기값을 null로 설정하는 것이 이후 체크에서 더 유리할 수 있기때문에 한번 고려해보시면 좋을거같습니다

```tsx
interface IModalContextProps {
  open: boolean;
  /** 모달 닫기 함수 */
  onClose: (() => void) | null; // @rushstack/no-new-null 걸림 ㅠ..
}
```

- 일단 완료하긴했지만 lint가 null 쓰는걸 잡아서........ 이후 확인 필요할듯 ㅠㅠ

## `Modal.Container` 모달이 노출되는 순간 모달에 포커싱 &  "ESC"를 통한 닫기 접근성

> 기본적으로 모달이 노출되는 순간 모달에 포커싱이 되는 접근성과 "ESC"를 통한 닫기 접근성은 필수적으로 들어가는게 좋을거같습니다

```tsx
const ModalContainer = ({ children }: IModalContainerProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const { open, onClose } = useModal();

  useEffect(() => {
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape" && open) {
        // 눌린 Key가 ESC면서 open=true 상태
        onClose!(); // 여기로 넘어왔다는건 확실하게 있다는거니까 타입 단언
      }
    };
    if (open) {
      // open=true가 되면 keydown 이벤트에 handleEscape 넣기
      document.addEventListener("keydown", handleEscape);
      containerRef.current?.focus();
    }
    return () => {
      // 언마운트 될 때 제거
      document.removeEventListener("keydown", handleEscape);
    };
  }, [open, onClose]);

  return (
    <ModalContainerWrapper ref={containerRef}>{children}</ModalContainerWrapper>
  );
};
```

- 완료!!

## useModal 훅 생성해서 오류 체크

> useContext를 직접 호출해서 사용하는 것보단 훅을 만들어서 해당 훅이 Context 범위 내에서 사용중인지도 체크하면서 사용하는게 더 효율적일수도있을거같습니다

```tsx
const useModal = () => {
  const context = useContext(ModalContext);
  if (!context) {
    throw new Error("Modal Context 내에서만 사용 가능합니다.");
  }
  return context;
};
```

- 완료!!
