### ISSUE TITLE
feat: ProfileRegistrationForm 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#59]
## 📌 작업 내용

ProfileRegistrationForm 

![Image](https://github.com/user-attachments/assets/76dd3f8a-c0dc-454c-a810-b6647e0ce195)

### props

- user?: { profile?: string; nickname: string; }
- onSubmit : function

## ✅ To-Do

- [x] 프로필 이미지 클릭 시 File 선택 박스 열리는지 확인
- [x] File 선택 박스에서 이미지 선택 시 Image에 적용되는지 확인
- [x] input 입력 시 값이 변경되는지 확인
- [x] props(user)가 있는 경우 profile / nickname이 정상적으로 적용되는지 확인
- [x] 등록 완료 누르면 onSubmit으로 console.log에 찍힌다. 

## 📝 참고사항

이미지 업로드는 아래와 같이 진행

1. 초기 상태는 Image 컴포넌트에 default image 출력된 상태
2. Image와 겹쳐있는 ImageUpload 클릭 -> 사용자 파일 업로드
3. 사용자가 업로드한 이미지로 Image 적용

### 선행 조건

- #6 
- #20  
- #12 
- #9
