### ISSUE TITLE
feat: ChatMessage 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#61]
## 📌 작업 내용

말풍선, 시간, (안 읽었을 때 1추가)
Text

![Image](https://github.com/user-attachments/assets/1abcd9fc-d39a-449b-a0b8-b6bccae585a5)

### props

ChatMsgProps {
  /** 채팅 메시지 내용 */
  msg: string;
  /** 채팅 보낸 유저가 나인지 타인인지 구분 */
  isMe: boolean;
  /** 해당 채팅이 그룹에서 마지막 메시지인지 구분,(시간 표시 유무 구분)*/
  isLastMsg: boolean;
  /** 해당 채팅을 읽었는지 구분 */
  isRead: boolean;
  /** 해당 메시지 보낸 시간 */
  creadtedAt: string;
}

## ✅ To-Do

- [x] isMe 값에 따라 보낸 시간, 읽었는지 여부(1) 의 위치가 바뀌는지 확인( isMe===true인 경우 왼쪽, 아닌 경우 오른쪽)
- [x] isLastMsg 값에 따라 시간을 보이는 유무가 조정이 되는지 확인
- [x] isRead 값에 따라 읽었는지 여부(1) 의 보이는 유무가 조정이 되는지 확인

### 선행 조건

- #3
