### ISSUE TITLE
feat: ChatBubble 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#62]
## 📌 작업 내용
채팅 Msg들 모아둔 부분, 여기에 프로필이미지 추가 

![Image](https://github.com/user-attachments/assets/26c5b494-9114-4616-8810-ff32a9676dcd)

### props

  /** 채팅리스트 */
  chats: Chat[];
  /** 채팅 보낸 유저가 나인지 타인인지 구분 */
  isMe: boolean;
  /** 프로필 이미지 URL 경로 */
  imgUrl: string

Chat {
  /** 채팅 메시지 내용 */
  msg: string;
  /** 해당 채팅이 그룹에서 마지막 메시지인지 구분,(시간 표시 유무 구분)*/
  isLastMsg: boolean;
  /** 해당 채팅을 읽었는지 구분 */
  isRead: boolean;
  /** 해당 메시지 보낸 시간 */
  creadtedAt: string;
}

## ✅ To-Do

- [x] props로 받은imgUrl 이용해서 Image 컴포넌트에 전달 잘 되는지 확인(type:round) (유저 profile 이미지)
- [x] isMe 값에 따라 유저 profile 이미지가 잘 숨겨 지는지 확인
- [x] chats 를 map으로 돌면서 ChatMessage 컴포넌트에 전달 잘 되고 있는지 확인

### 선행 조건

- #9 
- #61
