### ISSUE TITLE
feat: ChatMessages 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#63]
## 📌 작업 내용

1:1 전체 채팅 말풍선들

ChatBubble
댓글입력+작성 버튼까지 합친 부분
![Image](https://github.com/user-attachments/assets/b401bf8a-a8cb-43ea-8851-85668b1d8515)

### props

- ChatBubbles :  ChatBubble[] (참고사항 참고)
- onClick : function 

--------------------------------------

## ✅ To-Do

- [x] props로 전달 받은 ChatBubbles를 map으로 돌면서 ChatBubble 컴포넌트에 값이 잘 전달 되고 있는지 확인
- [ ] props로 전달 받은 onChange를 InputWithButton컴포넌트에 잘 전달 하고 있는지 확인(스토리북 console에 값찍어보기) 
- [x] props로 전달 받은 onClick을 InputWithButton컴포넌트에 잘 전달 하고 있는지 확인 (스토리북 console에 값찍어보기) 
- [x] InputWithButton 에 전달되는 placeholder 및 text는 여기서 생성하여 전달 잘 해주고 있는지 확인
- [x] 내부 input값은 여기서 관리 + onChange
(placeholder 문구 : "댓글을 입력하세요."  ,text : "작성")

### 선행 조건

- #62 
- #22 

InputWithButton {
onChange: function
onClick: function
placeholder:string
}

ChatBubble {
/** 채팅리스트 */
chats: Chat[];
/* 채팅 보낸 유저가 나인지 타인인지 구분 */
isMe: boolean;
/* 프로필 이미지 URL 경로 */
imgUrl: string
}

Chat {
/** 채팅 메시지 내용 */
msg: string;
/* 해당 채팅이 그룹에서 마지막 메시지인지 구분,(시간 표시 유무 구분)*/
isLastMsg: boolean;
/** 해당 채팅을 읽었는지 구분 */
isRead: boolean;
/* 해당 메시지 보낸 시간 */
creadtedAt: string;
}
