### ISSUE TITLE
feat: SearchHistoryItem 컴포넌트 개발

### ISSUE THREAD

**Issue by ppyom** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#67]
## 📌 작업 내용

SearchHistoryItem 

![Image](https://github.com/user-attachments/assets/b0f37ef0-39ee-4dcd-b946-6bcc89c11f80)

### props

- searchTerm: string
- onDeleteButtonClick: () => void
- onHistoryItemClick: function

## ✅ To-Do

- [ ] 임의로 입력한 searchTerm이 정상적으로 보여지는지 확인
- [ ] SearchHistoryItem 클릭 시 console.log(\`/search/${searchTerm}\`) 출력
- [ ] X 버튼(아이콘) 클릭 시 onDeleteButtonClick 실행 (console)
- [ ] icon, title를  IconWithText 컴포넌트에 전달 잘 되는지 확인

### 선행 조건

- #15 (X 아이콘??)
- #17
