### ISSUE TITLE
feat: Overlapping Image 컴포넌트 개발

### ISSUE THREAD

**Issue by JW-Ahn0** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#70]
## 📌 작업 내용

Overlapping Image 
![Image](https://github.com/user-attachments/assets/0457a146-204d-4242-a9c1-07c1c873fef9)

### props

- frontImgUrl : string
- backImgUrl: string 
- type: "round" | "square"

## ✅ To-Do

- [x]  props로 전달 받은 이미지 url이 이미지로 제대로 반영되는지
- [x]  props로 전달 받은 shape type이 제대로 반영되는지
- [x] no-image 상태에서 띄울 이미지 아무거나 /public 에 넣어두기, default-img.png
- [x]  alt 옵션은 '이미지1 ,' '이미지2' 
- [x] 스토리북에 2개의 아무 이미지 잘 출력되는지 확인

### 선행 조건

- #9
