### ISSUE TITLE
feat: Image 컴포넌트 개발

### ISSUE THREAD

**Issue by y0unj1NoH** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_FE#9]
## 📌 작업 내용

- Atom의 Image 컴포넌트의 기능 개발

- 정사각형 이미지
![Image](https://github.com/user-attachments/assets/5f5c6723-4072-458e-9195-c27b9993b7bd)
- 둥근 이미지
- ![Image](https://github.com/user-attachments/assets/ad04e387-ead9-4cfb-9ca7-112a0a3abe00)

### props

- type: "round" | "square"
- url : string

## ✅ To-Do

- [ ] props로 전달 받은 이미지 url이 이미지로 제대로 반영되는지
- [ ] props로 전달 받은 shape type이 제대로 반영되는지
- [ ] no-image 상태에서 띄울 이미지 아무거나 /public 에 넣어두기, default-img.png
- [ ] alt 옵션은 '이미지'
- [ ] 스토리북에 아무 이미지 잘 출력되는지 확인

## 📝 참고사항

2시간

**Comment by ppyom** [comment]
# Image 수정 

- #25 

## 수정 내용

- 기존에 img element만 사용 => div > img
- type 추가 (default)
- 기존 type(square, round)의 경우 1:1 비율 유지
- imgPath Default_Img를 default_img 변경

![Image](https://github.com/user-attachments/assets/1473b097-c571-4c9d-9f16-bfc65648a1bf)
